services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    env_file:
      # - /home/deploy/config/.env.common # Common environment variables
      - .env.staging # Staging environment variables override common variables
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gateway_app-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
volumes:
  rabbitmq_data:

networks:
  gateway_app-net:
    external: true
